import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from 'next/font/google';
import "./globals.css";
import ClientLayout from "./ClientLayout";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
     <body
  className={`${montserrat.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
>
        {/* Razorpay */}
        <script src="https://checkout.razorpay.com/v1/checkout.js"></script>

        <ClientLayout>{children}</ClientLayout>
        <Footer/>
      </body>
    </html>
  );
}
